#!/usr/bin/env python3
"""Build the Make IT STEM website.

Renders every page in src/pages/<lang>/ through the shared layout in
src/templates/ and writes plain static HTML that GitHub Pages serves as-is:

    src/pages/en/blog.html  ->  blog.html
    src/pages/it/blog.html  ->  it/blog.html

It also writes sitemap.xml (with hreflang alternates) and the redirect stubs
listed in src/site.toml.

Usage:
    python scripts/build.py            build once
    python scripts/build.py --serve    build, serve on http://localhost:8080, rebuild on change
    python scripts/build.py --check    exit 1 if the committed HTML is out of date (used in CI)

Requires Jinja2 (pip install -r requirements.txt).
"""
import argparse
import functools
import hashlib
import http.server
import sys
import threading
import time
import tomllib
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined, pass_context, select_autoescape
from jinja2.exceptions import TemplateError

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
ASSETS = ROOT / "assets"

# First line after <!DOCTYPE html> in every generated file. Also how the build
# recognises its own output when cleaning up pages that no longer exist.
MARKER = "Generated by scripts/build.py"


class BuildError(Exception):
    pass


# ── Loading ────────────────────────────────────────────────────────────────

def load_toml(path):
    with open(path, "rb") as f:
        return tomllib.load(f)


def flatten_keys(d, prefix=""):
    keys = set()
    for k, v in d.items():
        if isinstance(v, dict):
            keys |= flatten_keys(v, f"{prefix}{k}.")
        else:
            keys.add(prefix + k)
    return keys


def load_site():
    site = load_toml(SRC / "site.toml")
    langs = site["languages"]
    default = langs[0]["code"]

    strings = {l["code"]: load_toml(SRC / "i18n" / f"{l['code']}.toml") for l in langs}
    ref = flatten_keys(strings[default])
    for code, s in strings.items():
        missing, extra = ref - flatten_keys(s), flatten_keys(s) - ref
        if missing or extra:
            raise BuildError(
                f"src/i18n/{code}.toml does not match src/i18n/{default}.toml:\n"
                + "".join(f"  missing: {k}\n" for k in sorted(missing))
                + "".join(f"  extra:   {k}\n" for k in sorted(extra)))

    pages = {l["code"]: sorted(p.stem for p in (SRC / "pages" / l["code"]).glob("*.html")) for l in langs}
    for code, names in pages.items():
        if names != pages[default]:
            only_default = set(pages[default]) - set(names)
            only_here = set(names) - set(pages[default])
            raise BuildError(
                f"Every page must exist in every language (src/pages/{default}/ vs src/pages/{code}/):\n"
                + "".join(f"  missing in {code}: {n}.html\n" for n in sorted(only_default))
                + "".join(f"  missing in {default}: {n}.html\n" for n in sorted(only_here)))

    data = {p.stem: load_toml(p) for p in sorted((SRC / "data").glob("*.toml"))}
    return site, strings, pages[default], data


# ── URLs ───────────────────────────────────────────────────────────────────

def page_file(page):
    """URL path of a page inside its language folder ('' for the home page)."""
    return "" if page == "index" else f"{page}.html"


def absolute_url(site, lang, page):
    return f"{site['url']}/{lang['path']}{page_file(page)}"


def relative_url(root, lang, page):
    return f"{root}{lang['path']}{page_file(page)}" or "./"


def output_path(lang, page):
    return ROOT / lang["path"] / f"{page}.html"


# ── Rendering ──────────────────────────────────────────────────────────────

@functools.lru_cache(maxsize=None)
def _file_hash(path, mtime):
    # Normalise line endings so a Windows checkout (CRLF) and CI (LF) agree.
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()[:8]


@pass_context
def asset(ctx, path):
    """Link to a file in assets/, with a content hash so browsers never use a stale copy."""
    f = ASSETS / path
    if not f.is_file():
        raise BuildError(f"{ctx.name}: asset not found: assets/{path}")
    return f"{ctx['root']}assets/{path}?v={_file_hash(f, f.stat().st_mtime)}"


def _fail(message):
    raise BuildError(message)


def format_date(value, t, style="short"):
    months = t["dates"][f"months_{style}"]
    return f"{value.day} {months[value.month - 1]} {value.year}"


def make_env():
    env = Environment(
        loader=FileSystemLoader([SRC / "templates", SRC / "pages"]),
        autoescape=select_autoescape(["html"]),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.globals["asset"] = asset
    env.globals["fail"] = _fail
    env.globals["icon"] = env.get_template("partials/icons.html").module.icon
    env.filters["date"] = format_date
    return env


def with_marker(html, source):
    doctype = "<!DOCTYPE html>\n"
    if not html.startswith(doctype):
        raise BuildError(f"{source} must render starting with <!DOCTYPE html>")
    note = f"<!-- {MARKER} from {source}. Edit that file, not this one. -->\n"
    return doctype + note + html[len(doctype):]


def render_all():
    """Return {output Path: text} for the whole site."""
    site, strings, pages, data = load_site()
    env = make_env()
    langs = site["languages"]
    default = langs[0]
    out = {}

    for lang in langs:
        root = "../" * lang["path"].count("/")
        t = strings[lang["code"]]
        for page in pages:
            source = f"src/pages/{lang['code']}/{page}.html"
            ctx = {
                "site": site,
                "lang": lang,
                "t": t,
                "data": data,
                "page": page,
                "root": root,
                "source": source,
                "canonical": absolute_url(site, lang, page),
                "alternates": [dict(l, url=absolute_url(site, l, page), href=relative_url(root, l, page))
                               for l in langs],
                "default_url": absolute_url(site, default, page),
                "js_config": {
                    "gaId": site["ga_id"],
                    "privacyUrl": "privacy.html#cookies",
                    "cookie": t["cookie"],
                },
            }
            try:
                html = env.get_template(f"{lang['code']}/{page}.html").render(ctx)
            except TemplateError as e:
                where = f"{e.filename}:{e.lineno}" if getattr(e, "lineno", None) else source
                raise BuildError(f"{where}: {e.message}") from e
            out[output_path(lang, page)] = with_marker(html, source)

    for old, new in site.get("redirects", {}).items():
        html = env.get_template("redirect.html").render(
            site=site, lang=default, t=strings[default["code"]], root="",
            target=f"{new}.html", canonical=absolute_url(site, default, new))
        out[output_path(default, old)] = with_marker(html, "src/templates/redirect.html")

    out[ROOT / "sitemap.xml"] = render_sitemap(site, langs)
    return out


def render_sitemap(site, langs):
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             f"<!-- {MARKER} from src/site.toml [sitemap]. -->",
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
             '        xmlns:xhtml="http://www.w3.org/1999/xhtml">']
    for page, priority in site["sitemap"].items():
        for lang in langs:
            lines.append("  <url>")
            lines.append(f"    <loc>{absolute_url(site, lang, page)}</loc>")
            for alt in langs:
                lines.append(f'    <xhtml:link rel="alternate" hreflang="{alt["code"]}" href="{absolute_url(site, alt, page)}"/>')
            lines.append(f'    <xhtml:link rel="alternate" hreflang="x-default" href="{absolute_url(site, langs[0], page)}"/>')
            lines.append(f"    <priority>{priority}</priority>")
            lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


# ── Writing / checking ─────────────────────────────────────────────────────

def generated_files_on_disk():
    """Every HTML file at the site root or in a language folder that this script wrote."""
    site = load_toml(SRC / "site.toml")
    dirs = {ROOT / l["path"] for l in site["languages"]}
    found = set()
    for d in dirs:
        for f in d.glob("*.html"):
            with open(f, encoding="utf-8", errors="replace") as fh:
                if MARKER in fh.read(300):
                    found.add(f)
    return found


def read_normalised(path):
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None


def build(quiet=False):
    out = render_all()
    written = 0
    for path, text in out.items():
        if read_normalised(path) != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            written += 1
    stale = generated_files_on_disk() - set(out)
    for f in stale:
        f.unlink()
        print(f"  removed {f.relative_to(ROOT).as_posix()} (no longer has a source page)")
    if not quiet:
        print(f"Built {len(out)} files ({written} changed).")
    return out


def check():
    out = render_all()
    problems = [f"  out of date: {p.relative_to(ROOT).as_posix()}" for p, text in out.items()
                if read_normalised(p) != text]
    problems += [f"  stale:       {p.relative_to(ROOT).as_posix()}"
                 for p in generated_files_on_disk() - set(out)]
    if problems:
        print("The generated site does not match src/. Run `python scripts/build.py` and commit the result:")
        print("\n".join(sorted(problems)))
        return 1
    print(f"OK: all {len(out)} generated files are up to date.")
    return 0


# ── Dev server ─────────────────────────────────────────────────────────────

def snapshot():
    return {p: p.stat().st_mtime for d in (SRC, ASSETS) for p in d.rglob("*") if p.is_file()}


def watch(interval=0.5):
    before = snapshot()
    while True:
        time.sleep(interval)
        now = snapshot()
        if now != before:
            before = now
            try:
                build(quiet=True)
                print(time.strftime("[%H:%M:%S]"), "rebuilt")
            except Exception as e:  # keep serving; the next save retries
                print(time.strftime("[%H:%M:%S]"), f"Build failed: {type(e).__name__}: {e}")


class DevHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def log_message(self, fmt, *args):
        if len(args) > 1 and str(args[1]).startswith(("4", "5")):
            super().log_message(fmt, *args)


def serve(port):
    sys.stdout.reconfigure(line_buffering=True)  # show rebuild messages immediately, even when piped
    build()
    threading.Thread(target=watch, daemon=True).start()
    handler = functools.partial(DevHandler, directory=str(ROOT))
    with http.server.ThreadingHTTPServer(("127.0.0.1", port), handler) as httpd:
        print(f"Serving http://localhost:{port}/")
        for lang in load_toml(SRC / "site.toml")["languages"]:
            print(f"  {lang['label']}: http://localhost:{port}/{lang['path']}")
        print("Watching src/ and assets/ - edits rebuild automatically. Ctrl+C to stop.")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopped.")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--serve", action="store_true", help="serve locally and rebuild on change")
    mode.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    ap.add_argument("--port", type=int, default=8080)
    args = ap.parse_args()
    try:
        if args.check:
            return check()
        if args.serve:
            serve(args.port)
        else:
            build()
        return 0
    except BuildError as e:
        print(f"Build failed: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
